/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "order", schema = "road_to_b_dev")
public class Order implements Serializable {

	private static final long serialVersionUID = -347451341;

	private Integer id;
	private Integer sitId;
	private Integer tripId;
	private Integer userId;
	private Boolean isDisabled;

	public Order() {}

	public Order(Order value) {
		this.id = value.id;
		this.sitId = value.sitId;
		this.tripId = value.tripId;
		this.userId = value.userId;
		this.isDisabled = value.isDisabled;
	}

	public Order(
		Integer id,
		Integer sitId,
		Integer tripId,
		Integer userId,
		Boolean isDisabled
	) {
		this.id = id;
		this.sitId = sitId;
		this.tripId = tripId;
		this.userId = userId;
		this.isDisabled = isDisabled;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	@NotNull
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "sit_id", nullable = false, precision = 10)
	@NotNull
	public Integer getSitId() {
		return this.sitId;
	}

	public void setSitId(Integer sitId) {
		this.sitId = sitId;
	}

	@Column(name = "trip_id", nullable = false, precision = 10)
	@NotNull
	public Integer getTripId() {
		return this.tripId;
	}

	public void setTripId(Integer tripId) {
		this.tripId = tripId;
	}

	@Column(name = "user_id", nullable = false, precision = 10)
	@NotNull
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "is_disabled", nullable = false)
	@NotNull
	public Boolean getIsDisabled() {
		return this.isDisabled;
	}

	public void setIsDisabled(Boolean isDisabled) {
		this.isDisabled = isDisabled;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Order (");

		sb.append(id);
		sb.append(", ").append(sitId);
		sb.append(", ").append(tripId);
		sb.append(", ").append(userId);
		sb.append(", ").append(isDisabled);

		sb.append(")");
		return sb.toString();
	}
}
