/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "point", schema = "road_to_b_dev")
public class Point implements Serializable {

	private static final long serialVersionUID = -899458697;

	private Long    id;
	private String  name;
	private Double  longitude;
	private Double  latitude;
	private Boolean isDisabled;

	public Point() {}

	public Point(Point value) {
		this.id = value.id;
		this.name = value.name;
		this.longitude = value.longitude;
		this.latitude = value.latitude;
		this.isDisabled = value.isDisabled;
	}

	public Point(
		Long    id,
		String  name,
		Double  longitude,
		Double  latitude,
		Boolean isDisabled
	) {
		this.id = id;
		this.name = name;
		this.longitude = longitude;
		this.latitude = latitude;
		this.isDisabled = isDisabled;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 19)
	@NotNull
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	@NotNull
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "longitude", nullable = false, precision = 12)
	@NotNull
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "latitude", nullable = false, precision = 12)
	@NotNull
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "is_disabled", nullable = false)
	@NotNull
	public Boolean getIsDisabled() {
		return this.isDisabled;
	}

	public void setIsDisabled(Boolean isDisabled) {
		this.isDisabled = isDisabled;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Point (");

		sb.append(id);
		sb.append(", ").append(name);
		sb.append(", ").append(longitude);
		sb.append(", ").append(latitude);
		sb.append(", ").append(isDisabled);

		sb.append(")");
		return sb.toString();
	}
}
