/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "rout_point_mapping", schema = "road_to_b_dev")
public class RoutPointMapping implements Serializable {

	private static final long serialVersionUID = -566840260;

	private Integer routineId;
	private Long    pointId;
	private Integer ordering;
	private Boolean isDisabled;

	public RoutPointMapping() {}

	public RoutPointMapping(RoutPointMapping value) {
		this.routineId = value.routineId;
		this.pointId = value.pointId;
		this.ordering = value.ordering;
		this.isDisabled = value.isDisabled;
	}

	public RoutPointMapping(
		Integer routineId,
		Long    pointId,
		Integer ordering,
		Boolean isDisabled
	) {
		this.routineId = routineId;
		this.pointId = pointId;
		this.ordering = ordering;
		this.isDisabled = isDisabled;
	}

	@Column(name = "routine_id", nullable = false, precision = 10)
	@NotNull
	public Integer getRoutineId() {
		return this.routineId;
	}

	public void setRoutineId(Integer routineId) {
		this.routineId = routineId;
	}

	@Column(name = "point_id", precision = 19)
	public Long getPointId() {
		return this.pointId;
	}

	public void setPointId(Long pointId) {
		this.pointId = pointId;
	}

	@Column(name = "ordering", nullable = false, precision = 10)
	@NotNull
	public Integer getOrdering() {
		return this.ordering;
	}

	public void setOrdering(Integer ordering) {
		this.ordering = ordering;
	}

	@Column(name = "is_disabled", nullable = false)
	@NotNull
	public Boolean getIsDisabled() {
		return this.isDisabled;
	}

	public void setIsDisabled(Boolean isDisabled) {
		this.isDisabled = isDisabled;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("RoutPointMapping (");

		sb.append(routineId);
		sb.append(", ").append(pointId);
		sb.append(", ").append(ordering);
		sb.append(", ").append(isDisabled);

		sb.append(")");
		return sb.toString();
	}
}
