/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "sits", schema = "road_to_b_dev")
public class Sits implements Serializable {

	private static final long serialVersionUID = -1656364748;

	private Integer id;
	private Integer transportId;
	private Integer tripId;
	private Short   placeNumber;

	public Sits() {}

	public Sits(Sits value) {
		this.id = value.id;
		this.transportId = value.transportId;
		this.tripId = value.tripId;
		this.placeNumber = value.placeNumber;
	}

	public Sits(
		Integer id,
		Integer transportId,
		Integer tripId,
		Short   placeNumber
	) {
		this.id = id;
		this.transportId = transportId;
		this.tripId = tripId;
		this.placeNumber = placeNumber;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	@NotNull
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "transport_id", nullable = false, precision = 10)
	@NotNull
	public Integer getTransportId() {
		return this.transportId;
	}

	public void setTransportId(Integer transportId) {
		this.transportId = transportId;
	}

	@Column(name = "trip_id", nullable = false, precision = 10)
	@NotNull
	public Integer getTripId() {
		return this.tripId;
	}

	public void setTripId(Integer tripId) {
		this.tripId = tripId;
	}

	@Column(name = "place_number", nullable = false, precision = 5)
	@NotNull
	public Short getPlaceNumber() {
		return this.placeNumber;
	}

	public void setPlaceNumber(Short placeNumber) {
		this.placeNumber = placeNumber;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Sits (");

		sb.append(id);
		sb.append(", ").append(transportId);
		sb.append(", ").append(tripId);
		sb.append(", ").append(placeNumber);

		sb.append(")");
		return sb.toString();
	}
}
