/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "trip", schema = "road_to_b_dev")
public class Trip implements Serializable {

	private static final long serialVersionUID = 1488919906;

	private Integer   id;
	private Integer   transportId;
	private Integer   driverId;
	private Timestamp departureDate;
	private Timestamp arrivalDate;
	private Timestamp createdAt;

	public Trip() {}

	public Trip(Trip value) {
		this.id = value.id;
		this.transportId = value.transportId;
		this.driverId = value.driverId;
		this.departureDate = value.departureDate;
		this.arrivalDate = value.arrivalDate;
		this.createdAt = value.createdAt;
	}

	public Trip(
		Integer   id,
		Integer   transportId,
		Integer   driverId,
		Timestamp departureDate,
		Timestamp arrivalDate,
		Timestamp createdAt
	) {
		this.id = id;
		this.transportId = transportId;
		this.driverId = driverId;
		this.departureDate = departureDate;
		this.arrivalDate = arrivalDate;
		this.createdAt = createdAt;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	@NotNull
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "transport_id", nullable = false, precision = 10)
	@NotNull
	public Integer getTransportId() {
		return this.transportId;
	}

	public void setTransportId(Integer transportId) {
		this.transportId = transportId;
	}

	@Column(name = "driver_id", nullable = false, precision = 10)
	@NotNull
	public Integer getDriverId() {
		return this.driverId;
	}

	public void setDriverId(Integer driverId) {
		this.driverId = driverId;
	}

	@Column(name = "departure_date", nullable = false)
	@NotNull
	public Timestamp getDepartureDate() {
		return this.departureDate;
	}

	public void setDepartureDate(Timestamp departureDate) {
		this.departureDate = departureDate;
	}

	@Column(name = "arrival_date", nullable = false)
	@NotNull
	public Timestamp getArrivalDate() {
		return this.arrivalDate;
	}

	public void setArrivalDate(Timestamp arrivalDate) {
		this.arrivalDate = arrivalDate;
	}

	@Column(name = "created_at", nullable = false)
	@NotNull
	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Trip (");

		sb.append(id);
		sb.append(", ").append(transportId);
		sb.append(", ").append(driverId);
		sb.append(", ").append(departureDate);
		sb.append(", ").append(arrivalDate);
		sb.append(", ").append(createdAt);

		sb.append(")");
		return sb.toString();
	}
}
