/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "user_contact", schema = "road_to_b_dev")
public class UserContact implements Serializable {

	private static final long serialVersionUID = -1516552309;

	private Integer id;
	private Integer userId;
	private String  prop;
	private String  value;
	private Boolean isDisabled;

	public UserContact() {}

	public UserContact(UserContact value) {
		this.id = value.id;
		this.userId = value.userId;
		this.prop = value.prop;
		this.value = value.value;
		this.isDisabled = value.isDisabled;
	}

	public UserContact(
		Integer id,
		Integer userId,
		String  prop,
		String  value,
		Boolean isDisabled
	) {
		this.id = id;
		this.userId = userId;
		this.prop = prop;
		this.value = value;
		this.isDisabled = isDisabled;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	@NotNull
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id", nullable = false, precision = 10)
	@NotNull
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "prop", nullable = false, length = 128)
	@NotNull
	@Size(max = 128)
	public String getProp() {
		return this.prop;
	}

	public void setProp(String prop) {
		this.prop = prop;
	}

	@Column(name = "value", nullable = false, length = 1024)
	@NotNull
	@Size(max = 1024)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "is_disabled")
	public Boolean getIsDisabled() {
		return this.isDisabled;
	}

	public void setIsDisabled(Boolean isDisabled) {
		this.isDisabled = isDisabled;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("UserContact (");

		sb.append(id);
		sb.append(", ").append(userId);
		sb.append(", ").append(prop);
		sb.append(", ").append(value);
		sb.append(", ").append(isDisabled);

		sb.append(")");
		return sb.toString();
	}
}
