/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.nazymko.road_to_b.dao.tables.DriverProps;
import org.nazymko.road_to_b.dao.tables.records.DriverPropsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DriverPropsDao extends DAOImpl<DriverPropsRecord, org.nazymko.road_to_b.dao.tables.pojos.DriverProps, Integer> {

	/**
	 * Create a new DriverPropsDao without any configuration
	 */
	public DriverPropsDao() {
		super(DriverProps.DRIVER_PROPS, org.nazymko.road_to_b.dao.tables.pojos.DriverProps.class);
	}

	/**
	 * Create a new DriverPropsDao with an attached configuration
	 */
	public DriverPropsDao(Configuration configuration) {
		super(DriverProps.DRIVER_PROPS, org.nazymko.road_to_b.dao.tables.pojos.DriverProps.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.nazymko.road_to_b.dao.tables.pojos.DriverProps object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.DriverProps> fetchById(Integer... values) {
		return fetch(DriverProps.DRIVER_PROPS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.nazymko.road_to_b.dao.tables.pojos.DriverProps fetchOneById(Integer value) {
		return fetchOne(DriverProps.DRIVER_PROPS.ID, value);
	}

	/**
	 * Fetch records that have <code>driver_id IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.DriverProps> fetchByDriverId(Integer... values) {
		return fetch(DriverProps.DRIVER_PROPS.DRIVER_ID, values);
	}

	/**
	 * Fetch records that have <code>prop IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.DriverProps> fetchByProp(String... values) {
		return fetch(DriverProps.DRIVER_PROPS.PROP, values);
	}

	/**
	 * Fetch records that have <code>value IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.DriverProps> fetchByValue(String... values) {
		return fetch(DriverProps.DRIVER_PROPS.VALUE, values);
	}

	/**
	 * Fetch records that have <code>is_disabled IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.DriverProps> fetchByIsDisabled(Boolean... values) {
		return fetch(DriverProps.DRIVER_PROPS.IS_DISABLED, values);
	}
}
