/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.nazymko.road_to_b.dao.tables.Order;
import org.nazymko.road_to_b.dao.tables.records.OrderRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderDao extends DAOImpl<OrderRecord, org.nazymko.road_to_b.dao.tables.pojos.Order, Integer> {

	/**
	 * Create a new OrderDao without any configuration
	 */
	public OrderDao() {
		super(Order.ORDER, org.nazymko.road_to_b.dao.tables.pojos.Order.class);
	}

	/**
	 * Create a new OrderDao with an attached configuration
	 */
	public OrderDao(Configuration configuration) {
		super(Order.ORDER, org.nazymko.road_to_b.dao.tables.pojos.Order.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.nazymko.road_to_b.dao.tables.pojos.Order object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.Order> fetchById(Integer... values) {
		return fetch(Order.ORDER.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.nazymko.road_to_b.dao.tables.pojos.Order fetchOneById(Integer value) {
		return fetchOne(Order.ORDER.ID, value);
	}

	/**
	 * Fetch records that have <code>sit_id IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.Order> fetchBySitId(Integer... values) {
		return fetch(Order.ORDER.SIT_ID, values);
	}

	/**
	 * Fetch records that have <code>trip_id IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.Order> fetchByTripId(Integer... values) {
		return fetch(Order.ORDER.TRIP_ID, values);
	}

	/**
	 * Fetch records that have <code>user_id IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.Order> fetchByUserId(Integer... values) {
		return fetch(Order.ORDER.USER_ID, values);
	}

	/**
	 * Fetch records that have <code>is_disabled IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.Order> fetchByIsDisabled(Boolean... values) {
		return fetch(Order.ORDER.IS_DISABLED, values);
	}
}
