/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.nazymko.road_to_b.dao.tables.Routine;
import org.nazymko.road_to_b.dao.tables.records.RoutineRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoutineDao extends DAOImpl<RoutineRecord, org.nazymko.road_to_b.dao.tables.pojos.Routine, Integer> {

	/**
	 * Create a new RoutineDao without any configuration
	 */
	public RoutineDao() {
		super(Routine.ROUTINE, org.nazymko.road_to_b.dao.tables.pojos.Routine.class);
	}

	/**
	 * Create a new RoutineDao with an attached configuration
	 */
	public RoutineDao(Configuration configuration) {
		super(Routine.ROUTINE, org.nazymko.road_to_b.dao.tables.pojos.Routine.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.nazymko.road_to_b.dao.tables.pojos.Routine object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.Routine> fetchById(Integer... values) {
		return fetch(Routine.ROUTINE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.nazymko.road_to_b.dao.tables.pojos.Routine fetchOneById(Integer value) {
		return fetchOne(Routine.ROUTINE.ID, value);
	}

	/**
	 * Fetch records that have <code>description IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.Routine> fetchByDescription(String... values) {
		return fetch(Routine.ROUTINE.DESCRIPTION, values);
	}

	/**
	 * Fetch records that have <code>is_disabled IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.Routine> fetchByIsDisabled(Boolean... values) {
		return fetch(Routine.ROUTINE.IS_DISABLED, values);
	}
}
