/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.nazymko.road_to_b.dao.tables.Sits;
import org.nazymko.road_to_b.dao.tables.records.SitsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SitsDao extends DAOImpl<SitsRecord, org.nazymko.road_to_b.dao.tables.pojos.Sits, Integer> {

	/**
	 * Create a new SitsDao without any configuration
	 */
	public SitsDao() {
		super(Sits.SITS, org.nazymko.road_to_b.dao.tables.pojos.Sits.class);
	}

	/**
	 * Create a new SitsDao with an attached configuration
	 */
	public SitsDao(Configuration configuration) {
		super(Sits.SITS, org.nazymko.road_to_b.dao.tables.pojos.Sits.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.nazymko.road_to_b.dao.tables.pojos.Sits object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.Sits> fetchById(Integer... values) {
		return fetch(Sits.SITS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.nazymko.road_to_b.dao.tables.pojos.Sits fetchOneById(Integer value) {
		return fetchOne(Sits.SITS.ID, value);
	}

	/**
	 * Fetch records that have <code>transport_id IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.Sits> fetchByTransportId(Integer... values) {
		return fetch(Sits.SITS.TRANSPORT_ID, values);
	}

	/**
	 * Fetch records that have <code>trip_id IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.Sits> fetchByTripId(Integer... values) {
		return fetch(Sits.SITS.TRIP_ID, values);
	}

	/**
	 * Fetch records that have <code>place_number IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.Sits> fetchByPlaceNumber(Short... values) {
		return fetch(Sits.SITS.PLACE_NUMBER, values);
	}

	/**
	 * Fetch records that have <code>is_disabled IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.Sits> fetchByIsDisabled(Boolean... values) {
		return fetch(Sits.SITS.IS_DISABLED, values);
	}
}
