/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.nazymko.road_to_b.dao.tables.Transport;
import org.nazymko.road_to_b.dao.tables.records.TransportRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransportDao extends DAOImpl<TransportRecord, org.nazymko.road_to_b.dao.tables.pojos.Transport, Integer> {

	/**
	 * Create a new TransportDao without any configuration
	 */
	public TransportDao() {
		super(Transport.TRANSPORT, org.nazymko.road_to_b.dao.tables.pojos.Transport.class);
	}

	/**
	 * Create a new TransportDao with an attached configuration
	 */
	public TransportDao(Configuration configuration) {
		super(Transport.TRANSPORT, org.nazymko.road_to_b.dao.tables.pojos.Transport.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.nazymko.road_to_b.dao.tables.pojos.Transport object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.Transport> fetchById(Integer... values) {
		return fetch(Transport.TRANSPORT.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.nazymko.road_to_b.dao.tables.pojos.Transport fetchOneById(Integer value) {
		return fetchOne(Transport.TRANSPORT.ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.Transport> fetchByName(String... values) {
		return fetch(Transport.TRANSPORT.NAME, values);
	}

	/**
	 * Fetch records that have <code>is_disabled IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.Transport> fetchByIsDisabled(Boolean... values) {
		return fetch(Transport.TRANSPORT.IS_DISABLED, values);
	}
}
