/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.nazymko.road_to_b.dao.tables.TransportProps;
import org.nazymko.road_to_b.dao.tables.records.TransportPropsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransportPropsDao extends DAOImpl<TransportPropsRecord, org.nazymko.road_to_b.dao.tables.pojos.TransportProps, Integer> {

	/**
	 * Create a new TransportPropsDao without any configuration
	 */
	public TransportPropsDao() {
		super(TransportProps.TRANSPORT_PROPS, org.nazymko.road_to_b.dao.tables.pojos.TransportProps.class);
	}

	/**
	 * Create a new TransportPropsDao with an attached configuration
	 */
	public TransportPropsDao(Configuration configuration) {
		super(TransportProps.TRANSPORT_PROPS, org.nazymko.road_to_b.dao.tables.pojos.TransportProps.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.nazymko.road_to_b.dao.tables.pojos.TransportProps object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.TransportProps> fetchById(Integer... values) {
		return fetch(TransportProps.TRANSPORT_PROPS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.nazymko.road_to_b.dao.tables.pojos.TransportProps fetchOneById(Integer value) {
		return fetchOne(TransportProps.TRANSPORT_PROPS.ID, value);
	}

	/**
	 * Fetch records that have <code>transport_id IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.TransportProps> fetchByTransportId(Integer... values) {
		return fetch(TransportProps.TRANSPORT_PROPS.TRANSPORT_ID, values);
	}

	/**
	 * Fetch records that have <code>prop IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.TransportProps> fetchByProp(String... values) {
		return fetch(TransportProps.TRANSPORT_PROPS.PROP, values);
	}

	/**
	 * Fetch records that have <code>value IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.TransportProps> fetchByValue(String... values) {
		return fetch(TransportProps.TRANSPORT_PROPS.VALUE, values);
	}

	/**
	 * Fetch records that have <code>is_disabled IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.TransportProps> fetchByIsDisabled(Boolean... values) {
		return fetch(TransportProps.TRANSPORT_PROPS.IS_DISABLED, values);
	}
}
