/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables.daos;


import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.nazymko.road_to_b.dao.tables.Trip;
import org.nazymko.road_to_b.dao.tables.records.TripRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TripDao extends DAOImpl<TripRecord, org.nazymko.road_to_b.dao.tables.pojos.Trip, Integer> {

	/**
	 * Create a new TripDao without any configuration
	 */
	public TripDao() {
		super(Trip.TRIP, org.nazymko.road_to_b.dao.tables.pojos.Trip.class);
	}

	/**
	 * Create a new TripDao with an attached configuration
	 */
	public TripDao(Configuration configuration) {
		super(Trip.TRIP, org.nazymko.road_to_b.dao.tables.pojos.Trip.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.nazymko.road_to_b.dao.tables.pojos.Trip object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.Trip> fetchById(Integer... values) {
		return fetch(Trip.TRIP.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.nazymko.road_to_b.dao.tables.pojos.Trip fetchOneById(Integer value) {
		return fetchOne(Trip.TRIP.ID, value);
	}

	/**
	 * Fetch records that have <code>transport_id IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.Trip> fetchByTransportId(Integer... values) {
		return fetch(Trip.TRIP.TRANSPORT_ID, values);
	}

	/**
	 * Fetch records that have <code>driver_id IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.Trip> fetchByDriverId(Integer... values) {
		return fetch(Trip.TRIP.DRIVER_ID, values);
	}

	/**
	 * Fetch records that have <code>departure_date IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.Trip> fetchByDepartureDate(Timestamp... values) {
		return fetch(Trip.TRIP.DEPARTURE_DATE, values);
	}

	/**
	 * Fetch records that have <code>arrival_date IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.Trip> fetchByArrivalDate(Timestamp... values) {
		return fetch(Trip.TRIP.ARRIVAL_DATE, values);
	}

	/**
	 * Fetch records that have <code>created_at IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.Trip> fetchByCreatedAt(Timestamp... values) {
		return fetch(Trip.TRIP.CREATED_AT, values);
	}
}
