/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.nazymko.road_to_b.dao.tables.UserContact;
import org.nazymko.road_to_b.dao.tables.records.UserContactRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserContactDao extends DAOImpl<UserContactRecord, org.nazymko.road_to_b.dao.tables.pojos.UserContact, Integer> {

	/**
	 * Create a new UserContactDao without any configuration
	 */
	public UserContactDao() {
		super(UserContact.USER_CONTACT, org.nazymko.road_to_b.dao.tables.pojos.UserContact.class);
	}

	/**
	 * Create a new UserContactDao with an attached configuration
	 */
	public UserContactDao(Configuration configuration) {
		super(UserContact.USER_CONTACT, org.nazymko.road_to_b.dao.tables.pojos.UserContact.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.nazymko.road_to_b.dao.tables.pojos.UserContact object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.UserContact> fetchById(Integer... values) {
		return fetch(UserContact.USER_CONTACT.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.nazymko.road_to_b.dao.tables.pojos.UserContact fetchOneById(Integer value) {
		return fetchOne(UserContact.USER_CONTACT.ID, value);
	}

	/**
	 * Fetch records that have <code>user_id IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.UserContact> fetchByUserId(Integer... values) {
		return fetch(UserContact.USER_CONTACT.USER_ID, values);
	}

	/**
	 * Fetch records that have <code>prop IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.UserContact> fetchByProp(String... values) {
		return fetch(UserContact.USER_CONTACT.PROP, values);
	}

	/**
	 * Fetch records that have <code>value IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.UserContact> fetchByValue(String... values) {
		return fetch(UserContact.USER_CONTACT.VALUE, values);
	}

	/**
	 * Fetch records that have <code>is_disabled IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.UserContact> fetchByIsDisabled(Boolean... values) {
		return fetch(UserContact.USER_CONTACT.IS_DISABLED, values);
	}
}
