/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.nazymko.road_to_b.dao.tables.User;
import org.nazymko.road_to_b.dao.tables.records.UserRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDao extends DAOImpl<UserRecord, org.nazymko.road_to_b.dao.tables.pojos.User, Integer> {

	/**
	 * Create a new UserDao without any configuration
	 */
	public UserDao() {
		super(User.USER, org.nazymko.road_to_b.dao.tables.pojos.User.class);
	}

	/**
	 * Create a new UserDao with an attached configuration
	 */
	public UserDao(Configuration configuration) {
		super(User.USER, org.nazymko.road_to_b.dao.tables.pojos.User.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(org.nazymko.road_to_b.dao.tables.pojos.User object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.User> fetchById(Integer... values) {
		return fetch(User.USER.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.nazymko.road_to_b.dao.tables.pojos.User fetchOneById(Integer value) {
		return fetchOne(User.USER.ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.User> fetchByName(String... values) {
		return fetch(User.USER.NAME, values);
	}

	/**
	 * Fetch records that have <code>is_disabled IN (values)</code>
	 */
	public List<org.nazymko.road_to_b.dao.tables.pojos.User> fetchByIsDisabled(Boolean... values) {
		return fetch(User.USER.IS_DISABLED, values);
	}
}
