/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.nazymko.road_to_b.dao.Keys;
import org.nazymko.road_to_b.dao.RoadToBDev;
import org.nazymko.road_to_b.dao.tables.records.DriverPropsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DriverProps extends TableImpl<DriverPropsRecord> {

	private static final long serialVersionUID = -605299217;

	/**
	 * The reference instance of <code>road_to_b_dev.driver_props</code>
	 */
	public static final DriverProps DRIVER_PROPS = new DriverProps();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<DriverPropsRecord> getRecordType() {
		return DriverPropsRecord.class;
	}

	/**
	 * The column <code>road_to_b_dev.driver_props.id</code>.
	 */
	public final TableField<DriverPropsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>road_to_b_dev.driver_props.driver_id</code>.
	 */
	public final TableField<DriverPropsRecord, Integer> DRIVER_ID = createField("driver_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>road_to_b_dev.driver_props.prop</code>.
	 */
	public final TableField<DriverPropsRecord, String> PROP = createField("prop", org.jooq.impl.SQLDataType.VARCHAR.length(1024).nullable(false), this, "");

	/**
	 * The column <code>road_to_b_dev.driver_props.value</code>.
	 */
	public final TableField<DriverPropsRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR.length(1024).nullable(false), this, "");

	/**
	 * The column <code>road_to_b_dev.driver_props.is_disabled</code>.
	 */
	public final TableField<DriverPropsRecord, Boolean> IS_DISABLED = createField("is_disabled", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

	/**
	 * Create a <code>road_to_b_dev.driver_props</code> table reference
	 */
	public DriverProps() {
		this("driver_props", null);
	}

	/**
	 * Create an aliased <code>road_to_b_dev.driver_props</code> table reference
	 */
	public DriverProps(String alias) {
		this(alias, DRIVER_PROPS);
	}

	private DriverProps(String alias, Table<DriverPropsRecord> aliased) {
		this(alias, aliased, null);
	}

	private DriverProps(String alias, Table<DriverPropsRecord> aliased, Field<?>[] parameters) {
		super(alias, RoadToBDev.ROAD_TO_B_DEV, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<DriverPropsRecord, Integer> getIdentity() {
		return Keys.IDENTITY_DRIVER_PROPS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<DriverPropsRecord> getPrimaryKey() {
		return Keys.KEY_DRIVER_PROPS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<DriverPropsRecord>> getKeys() {
		return Arrays.<UniqueKey<DriverPropsRecord>>asList(Keys.KEY_DRIVER_PROPS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<DriverPropsRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<DriverPropsRecord, ?>>asList(Keys.DRIVER_PROPS_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DriverProps as(String alias) {
		return new DriverProps(alias, this);
	}

	/**
	 * Rename this table
	 */
	public DriverProps rename(String name) {
		return new DriverProps(name, null);
	}
}
