/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.nazymko.road_to_b.dao.Keys;
import org.nazymko.road_to_b.dao.RoadToBDev;
import org.nazymko.road_to_b.dao.tables.records.DriverTypesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DriverTypes extends TableImpl<DriverTypesRecord> {

	private static final long serialVersionUID = -377493486;

	/**
	 * The reference instance of <code>road_to_b_dev.driver_types</code>
	 */
	public static final DriverTypes DRIVER_TYPES = new DriverTypes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<DriverTypesRecord> getRecordType() {
		return DriverTypesRecord.class;
	}

	/**
	 * The column <code>road_to_b_dev.driver_types.id</code>.
	 */
	public final TableField<DriverTypesRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>road_to_b_dev.driver_types.description</code>.
	 */
	public final TableField<DriverTypesRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(1024).nullable(false), this, "");

	/**
	 * The column <code>road_to_b_dev.driver_types.name</code>.
	 */
	public final TableField<DriverTypesRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(1024).nullable(false), this, "");

	/**
	 * The column <code>road_to_b_dev.driver_types.is_disabled</code>.
	 */
	public final TableField<DriverTypesRecord, Boolean> IS_DISABLED = createField("is_disabled", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

	/**
	 * Create a <code>road_to_b_dev.driver_types</code> table reference
	 */
	public DriverTypes() {
		this("driver_types", null);
	}

	/**
	 * Create an aliased <code>road_to_b_dev.driver_types</code> table reference
	 */
	public DriverTypes(String alias) {
		this(alias, DRIVER_TYPES);
	}

	private DriverTypes(String alias, Table<DriverTypesRecord> aliased) {
		this(alias, aliased, null);
	}

	private DriverTypes(String alias, Table<DriverTypesRecord> aliased, Field<?>[] parameters) {
		super(alias, RoadToBDev.ROAD_TO_B_DEV, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<DriverTypesRecord> getPrimaryKey() {
		return Keys.KEY_DRIVER_TYPES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<DriverTypesRecord>> getKeys() {
		return Arrays.<UniqueKey<DriverTypesRecord>>asList(Keys.KEY_DRIVER_TYPES_PRIMARY, Keys.KEY_DRIVER_TYPES_UNIQUE_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DriverTypes as(String alias) {
		return new DriverTypes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public DriverTypes rename(String name) {
		return new DriverTypes(name, null);
	}
}
