/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.nazymko.road_to_b.dao.Keys;
import org.nazymko.road_to_b.dao.RoadToBDev;
import org.nazymko.road_to_b.dao.tables.records.RoutPointMappingRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoutPointMapping extends TableImpl<RoutPointMappingRecord> {

	private static final long serialVersionUID = -230701550;

	/**
	 * The reference instance of <code>road_to_b_dev.rout_point_mapping</code>
	 */
	public static final RoutPointMapping ROUT_POINT_MAPPING = new RoutPointMapping();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RoutPointMappingRecord> getRecordType() {
		return RoutPointMappingRecord.class;
	}

	/**
	 * The column <code>road_to_b_dev.rout_point_mapping.routine_id</code>.
	 */
	public final TableField<RoutPointMappingRecord, Integer> ROUTINE_ID = createField("routine_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>road_to_b_dev.rout_point_mapping.point_id</code>.
	 */
	public final TableField<RoutPointMappingRecord, Long> POINT_ID = createField("point_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>road_to_b_dev.rout_point_mapping.ordering</code>.
	 */
	public final TableField<RoutPointMappingRecord, Integer> ORDERING = createField("ordering", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>road_to_b_dev.rout_point_mapping.is_disabled</code>.
	 */
	public final TableField<RoutPointMappingRecord, Boolean> IS_DISABLED = createField("is_disabled", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

	/**
	 * Create a <code>road_to_b_dev.rout_point_mapping</code> table reference
	 */
	public RoutPointMapping() {
		this("rout_point_mapping", null);
	}

	/**
	 * Create an aliased <code>road_to_b_dev.rout_point_mapping</code> table reference
	 */
	public RoutPointMapping(String alias) {
		this(alias, ROUT_POINT_MAPPING);
	}

	private RoutPointMapping(String alias, Table<RoutPointMappingRecord> aliased) {
		this(alias, aliased, null);
	}

	private RoutPointMapping(String alias, Table<RoutPointMappingRecord> aliased, Field<?>[] parameters) {
		super(alias, RoadToBDev.ROAD_TO_B_DEV, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<RoutPointMappingRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<RoutPointMappingRecord, ?>>asList(Keys.ROUT_POINT_MAPPING_IBFK_1, Keys.ROUT_POINT_MAPPING_IBFK_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoutPointMapping as(String alias) {
		return new RoutPointMapping(alias, this);
	}

	/**
	 * Rename this table
	 */
	public RoutPointMapping rename(String name) {
		return new RoutPointMapping(name, null);
	}
}
