/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.nazymko.road_to_b.dao.Keys;
import org.nazymko.road_to_b.dao.RoadToBDev;
import org.nazymko.road_to_b.dao.tables.records.TransportPropsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransportProps extends TableImpl<TransportPropsRecord> {

	private static final long serialVersionUID = 917997542;

	/**
	 * The reference instance of <code>road_to_b_dev.transport_props</code>
	 */
	public static final TransportProps TRANSPORT_PROPS = new TransportProps();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TransportPropsRecord> getRecordType() {
		return TransportPropsRecord.class;
	}

	/**
	 * The column <code>road_to_b_dev.transport_props.id</code>.
	 */
	public final TableField<TransportPropsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>road_to_b_dev.transport_props.transport_id</code>.
	 */
	public final TableField<TransportPropsRecord, Integer> TRANSPORT_ID = createField("transport_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>road_to_b_dev.transport_props.prop</code>.
	 */
	public final TableField<TransportPropsRecord, String> PROP = createField("prop", org.jooq.impl.SQLDataType.VARCHAR.length(1024).nullable(false), this, "");

	/**
	 * The column <code>road_to_b_dev.transport_props.value</code>.
	 */
	public final TableField<TransportPropsRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR.length(1024).nullable(false), this, "");

	/**
	 * The column <code>road_to_b_dev.transport_props.is_disabled</code>.
	 */
	public final TableField<TransportPropsRecord, Boolean> IS_DISABLED = createField("is_disabled", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>road_to_b_dev.transport_props</code> table reference
	 */
	public TransportProps() {
		this("transport_props", null);
	}

	/**
	 * Create an aliased <code>road_to_b_dev.transport_props</code> table reference
	 */
	public TransportProps(String alias) {
		this(alias, TRANSPORT_PROPS);
	}

	private TransportProps(String alias, Table<TransportPropsRecord> aliased) {
		this(alias, aliased, null);
	}

	private TransportProps(String alias, Table<TransportPropsRecord> aliased, Field<?>[] parameters) {
		super(alias, RoadToBDev.ROAD_TO_B_DEV, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<TransportPropsRecord, Integer> getIdentity() {
		return Keys.IDENTITY_TRANSPORT_PROPS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TransportPropsRecord> getPrimaryKey() {
		return Keys.KEY_TRANSPORT_PROPS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TransportPropsRecord>> getKeys() {
		return Arrays.<UniqueKey<TransportPropsRecord>>asList(Keys.KEY_TRANSPORT_PROPS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransportProps as(String alias) {
		return new TransportProps(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TransportProps rename(String name) {
		return new TransportProps(name, null);
	}
}
