/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.nazymko.road_to_b.dao.Keys;
import org.nazymko.road_to_b.dao.RoadToBDev;
import org.nazymko.road_to_b.dao.tables.records.TransportRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transport extends TableImpl<TransportRecord> {

	private static final long serialVersionUID = 763850363;

	/**
	 * The reference instance of <code>road_to_b_dev.transport</code>
	 */
	public static final Transport TRANSPORT = new Transport();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TransportRecord> getRecordType() {
		return TransportRecord.class;
	}

	/**
	 * The column <code>road_to_b_dev.transport.id</code>.
	 */
	public final TableField<TransportRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>road_to_b_dev.transport.name</code>.
	 */
	public final TableField<TransportRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(1024).nullable(false), this, "");

	/**
	 * Create a <code>road_to_b_dev.transport</code> table reference
	 */
	public Transport() {
		this("transport", null);
	}

	/**
	 * Create an aliased <code>road_to_b_dev.transport</code> table reference
	 */
	public Transport(String alias) {
		this(alias, TRANSPORT);
	}

	private Transport(String alias, Table<TransportRecord> aliased) {
		this(alias, aliased, null);
	}

	private Transport(String alias, Table<TransportRecord> aliased, Field<?>[] parameters) {
		super(alias, RoadToBDev.ROAD_TO_B_DEV, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TransportRecord> getPrimaryKey() {
		return Keys.KEY_TRANSPORT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TransportRecord>> getKeys() {
		return Arrays.<UniqueKey<TransportRecord>>asList(Keys.KEY_TRANSPORT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Transport as(String alias) {
		return new Transport(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Transport rename(String name) {
		return new Transport(name, null);
	}
}
