/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.nazymko.road_to_b.dao.Keys;
import org.nazymko.road_to_b.dao.RoadToBDev;
import org.nazymko.road_to_b.dao.tables.records.TripRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Trip extends TableImpl<TripRecord> {

	private static final long serialVersionUID = -884949688;

	/**
	 * The reference instance of <code>road_to_b_dev.trip</code>
	 */
	public static final Trip TRIP = new Trip();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TripRecord> getRecordType() {
		return TripRecord.class;
	}

	/**
	 * The column <code>road_to_b_dev.trip.id</code>.
	 */
	public final TableField<TripRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>road_to_b_dev.trip.transport_id</code>.
	 */
	public final TableField<TripRecord, Integer> TRANSPORT_ID = createField("transport_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>road_to_b_dev.trip.driver_id</code>.
	 */
	public final TableField<TripRecord, Integer> DRIVER_ID = createField("driver_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>road_to_b_dev.trip.departure_date</code>.
	 */
	public final TableField<TripRecord, Timestamp> DEPARTURE_DATE = createField("departure_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>road_to_b_dev.trip.arrival_date</code>.
	 */
	public final TableField<TripRecord, Timestamp> ARRIVAL_DATE = createField("arrival_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>road_to_b_dev.trip.created_at</code>.
	 */
	public final TableField<TripRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>road_to_b_dev.trip</code> table reference
	 */
	public Trip() {
		this("trip", null);
	}

	/**
	 * Create an aliased <code>road_to_b_dev.trip</code> table reference
	 */
	public Trip(String alias) {
		this(alias, TRIP);
	}

	private Trip(String alias, Table<TripRecord> aliased) {
		this(alias, aliased, null);
	}

	private Trip(String alias, Table<TripRecord> aliased, Field<?>[] parameters) {
		super(alias, RoadToBDev.ROAD_TO_B_DEV, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TripRecord> getPrimaryKey() {
		return Keys.KEY_TRIP_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TripRecord>> getKeys() {
		return Arrays.<UniqueKey<TripRecord>>asList(Keys.KEY_TRIP_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Trip as(String alias) {
		return new Trip(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Trip rename(String name) {
		return new Trip(name, null);
	}
}
