/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.nazymko.road_to_b.dao.Keys;
import org.nazymko.road_to_b.dao.RoadToBDev;
import org.nazymko.road_to_b.dao.tables.records.UserContactRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserContact extends TableImpl<UserContactRecord> {

	private static final long serialVersionUID = -557325788;

	/**
	 * The reference instance of <code>road_to_b_dev.user_contact</code>
	 */
	public static final UserContact USER_CONTACT = new UserContact();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<UserContactRecord> getRecordType() {
		return UserContactRecord.class;
	}

	/**
	 * The column <code>road_to_b_dev.user_contact.id</code>.
	 */
	public final TableField<UserContactRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>road_to_b_dev.user_contact.user_id</code>.
	 */
	public final TableField<UserContactRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>road_to_b_dev.user_contact.prop</code>.
	 */
	public final TableField<UserContactRecord, String> PROP = createField("prop", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>road_to_b_dev.user_contact.value</code>.
	 */
	public final TableField<UserContactRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR.length(1024).nullable(false), this, "");

	/**
	 * The column <code>road_to_b_dev.user_contact.is_disabled</code>.
	 */
	public final TableField<UserContactRecord, Boolean> IS_DISABLED = createField("is_disabled", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * Create a <code>road_to_b_dev.user_contact</code> table reference
	 */
	public UserContact() {
		this("user_contact", null);
	}

	/**
	 * Create an aliased <code>road_to_b_dev.user_contact</code> table reference
	 */
	public UserContact(String alias) {
		this(alias, USER_CONTACT);
	}

	private UserContact(String alias, Table<UserContactRecord> aliased) {
		this(alias, aliased, null);
	}

	private UserContact(String alias, Table<UserContactRecord> aliased, Field<?>[] parameters) {
		super(alias, RoadToBDev.ROAD_TO_B_DEV, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<UserContactRecord> getPrimaryKey() {
		return Keys.KEY_USER_CONTACT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<UserContactRecord>> getKeys() {
		return Arrays.<UniqueKey<UserContactRecord>>asList(Keys.KEY_USER_CONTACT_PRIMARY, Keys.KEY_USER_CONTACT_UNIQUE_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<UserContactRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<UserContactRecord, ?>>asList(Keys.USER_CONTACT_IBFK_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserContact as(String alias) {
		return new UserContact(alias, this);
	}

	/**
	 * Rename this table
	 */
	public UserContact rename(String name) {
		return new UserContact(name, null);
	}
}
