/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables.records;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.nazymko.road_to_b.dao.tables.DriverProps;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "driver_props", schema = "road_to_b_dev")
public class DriverPropsRecord extends UpdatableRecordImpl<DriverPropsRecord> implements Record4<Integer, Integer, String, String> {

	private static final long serialVersionUID = 1353964955;

	/**
	 * Setter for <code>road_to_b_dev.driver_props.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>road_to_b_dev.driver_props.id</code>.
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	@NotNull
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>road_to_b_dev.driver_props.driver_id</code>.
	 */
	public void setDriverId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>road_to_b_dev.driver_props.driver_id</code>.
	 */
	@Column(name = "driver_id", nullable = false, precision = 10)
	@NotNull
	public Integer getDriverId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>road_to_b_dev.driver_props.prop</code>.
	 */
	public void setProp(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>road_to_b_dev.driver_props.prop</code>.
	 */
	@Column(name = "prop", nullable = false, length = 1024)
	@NotNull
	@Size(max = 1024)
	public String getProp() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>road_to_b_dev.driver_props.value</code>.
	 */
	public void setValue(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>road_to_b_dev.driver_props.value</code>.
	 */
	@Column(name = "value", nullable = false, length = 1024)
	@NotNull
	@Size(max = 1024)
	public String getValue() {
		return (String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Integer, String, String> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Integer, String, String> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return DriverProps.DRIVER_PROPS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return DriverProps.DRIVER_PROPS.DRIVER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return DriverProps.DRIVER_PROPS.PROP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return DriverProps.DRIVER_PROPS.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getDriverId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getProp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DriverPropsRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DriverPropsRecord value2(Integer value) {
		setDriverId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DriverPropsRecord value3(String value) {
		setProp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DriverPropsRecord value4(String value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DriverPropsRecord values(Integer value1, Integer value2, String value3, String value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DriverPropsRecord
	 */
	public DriverPropsRecord() {
		super(DriverProps.DRIVER_PROPS);
	}

	/**
	 * Create a detached, initialised DriverPropsRecord
	 */
	public DriverPropsRecord(Integer id, Integer driverId, String prop, String value) {
		super(DriverProps.DRIVER_PROPS);

		setValue(0, id);
		setValue(1, driverId);
		setValue(2, prop);
		setValue(3, value);
	}
}
