/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables.records;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.nazymko.road_to_b.dao.tables.Order;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "order", schema = "road_to_b_dev")
public class OrderRecord extends UpdatableRecordImpl<OrderRecord> implements Record5<Integer, Integer, Integer, Integer, Boolean> {

	private static final long serialVersionUID = 1759452243;

	/**
	 * Setter for <code>road_to_b_dev.order.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>road_to_b_dev.order.id</code>.
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	@NotNull
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>road_to_b_dev.order.sit_id</code>.
	 */
	public void setSitId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>road_to_b_dev.order.sit_id</code>.
	 */
	@Column(name = "sit_id", nullable = false, precision = 10)
	@NotNull
	public Integer getSitId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>road_to_b_dev.order.trip_id</code>.
	 */
	public void setTripId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>road_to_b_dev.order.trip_id</code>.
	 */
	@Column(name = "trip_id", nullable = false, precision = 10)
	@NotNull
	public Integer getTripId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>road_to_b_dev.order.user_id</code>.
	 */
	public void setUserId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>road_to_b_dev.order.user_id</code>.
	 */
	@Column(name = "user_id", nullable = false, precision = 10)
	@NotNull
	public Integer getUserId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>road_to_b_dev.order.is_disabled</code>.
	 */
	public void setIsDisabled(Boolean value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>road_to_b_dev.order.is_disabled</code>.
	 */
	@Column(name = "is_disabled", nullable = false)
	@NotNull
	public Boolean getIsDisabled() {
		return (Boolean) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, Integer, Integer, Boolean> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, Integer, Integer, Boolean> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Order.ORDER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Order.ORDER.SIT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Order.ORDER.TRIP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Order.ORDER.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field5() {
		return Order.ORDER.IS_DISABLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getSitId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getTripId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value5() {
		return getIsDisabled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrderRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrderRecord value2(Integer value) {
		setSitId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrderRecord value3(Integer value) {
		setTripId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrderRecord value4(Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrderRecord value5(Boolean value) {
		setIsDisabled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrderRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Boolean value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached OrderRecord
	 */
	public OrderRecord() {
		super(Order.ORDER);
	}

	/**
	 * Create a detached, initialised OrderRecord
	 */
	public OrderRecord(Integer id, Integer sitId, Integer tripId, Integer userId, Boolean isDisabled) {
		super(Order.ORDER);

		setValue(0, id);
		setValue(1, sitId);
		setValue(2, tripId);
		setValue(3, userId);
		setValue(4, isDisabled);
	}
}
