/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables.records;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;
import org.nazymko.road_to_b.dao.tables.RoutPointMapping;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "rout_point_mapping", schema = "road_to_b_dev")
public class RoutPointMappingRecord extends TableRecordImpl<RoutPointMappingRecord> implements Record4<Integer, Long, Integer, Boolean> {

	private static final long serialVersionUID = 1465236473;

	/**
	 * Setter for <code>road_to_b_dev.rout_point_mapping.routine_id</code>.
	 */
	public void setRoutineId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>road_to_b_dev.rout_point_mapping.routine_id</code>.
	 */
	@Column(name = "routine_id", nullable = false, precision = 10)
	@NotNull
	public Integer getRoutineId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>road_to_b_dev.rout_point_mapping.point_id</code>.
	 */
	public void setPointId(Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>road_to_b_dev.rout_point_mapping.point_id</code>.
	 */
	@Column(name = "point_id", precision = 19)
	public Long getPointId() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>road_to_b_dev.rout_point_mapping.ordering</code>.
	 */
	public void setOrdering(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>road_to_b_dev.rout_point_mapping.ordering</code>.
	 */
	@Column(name = "ordering", nullable = false, precision = 10)
	@NotNull
	public Integer getOrdering() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>road_to_b_dev.rout_point_mapping.is_disabled</code>.
	 */
	public void setIsDisabled(Boolean value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>road_to_b_dev.rout_point_mapping.is_disabled</code>.
	 */
	@Column(name = "is_disabled", nullable = false)
	@NotNull
	public Boolean getIsDisabled() {
		return (Boolean) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Long, Integer, Boolean> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Long, Integer, Boolean> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return RoutPointMapping.ROUT_POINT_MAPPING.ROUTINE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return RoutPointMapping.ROUT_POINT_MAPPING.POINT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return RoutPointMapping.ROUT_POINT_MAPPING.ORDERING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field4() {
		return RoutPointMapping.ROUT_POINT_MAPPING.IS_DISABLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getRoutineId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getPointId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getOrdering();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value4() {
		return getIsDisabled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoutPointMappingRecord value1(Integer value) {
		setRoutineId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoutPointMappingRecord value2(Long value) {
		setPointId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoutPointMappingRecord value3(Integer value) {
		setOrdering(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoutPointMappingRecord value4(Boolean value) {
		setIsDisabled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoutPointMappingRecord values(Integer value1, Long value2, Integer value3, Boolean value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RoutPointMappingRecord
	 */
	public RoutPointMappingRecord() {
		super(RoutPointMapping.ROUT_POINT_MAPPING);
	}

	/**
	 * Create a detached, initialised RoutPointMappingRecord
	 */
	public RoutPointMappingRecord(Integer routineId, Long pointId, Integer ordering, Boolean isDisabled) {
		super(RoutPointMapping.ROUT_POINT_MAPPING);

		setValue(0, routineId);
		setValue(1, pointId);
		setValue(2, ordering);
		setValue(3, isDisabled);
	}
}
