/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao.tables.records;


import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.nazymko.road_to_b.dao.tables.TransportProps;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "transport_props", schema = "road_to_b_dev")
public class TransportPropsRecord extends UpdatableRecordImpl<TransportPropsRecord> implements Record5<Integer, Integer, String, String, Boolean> {

	private static final long serialVersionUID = 865727513;

	/**
	 * Setter for <code>road_to_b_dev.transport_props.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>road_to_b_dev.transport_props.id</code>.
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	@NotNull
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>road_to_b_dev.transport_props.transport_id</code>.
	 */
	public void setTransportId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>road_to_b_dev.transport_props.transport_id</code>.
	 */
	@Column(name = "transport_id", nullable = false, precision = 10)
	@NotNull
	public Integer getTransportId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>road_to_b_dev.transport_props.prop</code>.
	 */
	public void setProp(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>road_to_b_dev.transport_props.prop</code>.
	 */
	@Column(name = "prop", nullable = false, length = 1024)
	@NotNull
	@Size(max = 1024)
	public String getProp() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>road_to_b_dev.transport_props.value</code>.
	 */
	public void setValue(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>road_to_b_dev.transport_props.value</code>.
	 */
	@Column(name = "value", nullable = false, length = 1024)
	@NotNull
	@Size(max = 1024)
	public String getValue() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>road_to_b_dev.transport_props.is_disabled</code>.
	 */
	public void setIsDisabled(Boolean value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>road_to_b_dev.transport_props.is_disabled</code>.
	 */
	@Column(name = "is_disabled", nullable = false)
	@NotNull
	public Boolean getIsDisabled() {
		return (Boolean) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, String, String, Boolean> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, String, String, Boolean> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return TransportProps.TRANSPORT_PROPS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return TransportProps.TRANSPORT_PROPS.TRANSPORT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return TransportProps.TRANSPORT_PROPS.PROP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return TransportProps.TRANSPORT_PROPS.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field5() {
		return TransportProps.TRANSPORT_PROPS.IS_DISABLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getTransportId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getProp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value5() {
		return getIsDisabled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransportPropsRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransportPropsRecord value2(Integer value) {
		setTransportId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransportPropsRecord value3(String value) {
		setProp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransportPropsRecord value4(String value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransportPropsRecord value5(Boolean value) {
		setIsDisabled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransportPropsRecord values(Integer value1, Integer value2, String value3, String value4, Boolean value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TransportPropsRecord
	 */
	public TransportPropsRecord() {
		super(TransportProps.TRANSPORT_PROPS);
	}

	/**
	 * Create a detached, initialised TransportPropsRecord
	 */
	public TransportPropsRecord(Integer id, Integer transportId, String prop, String value, Boolean isDisabled) {
		super(TransportProps.TRANSPORT_PROPS);

		setValue(0, id);
		setValue(1, transportId);
		setValue(2, prop);
		setValue(3, value);
		setValue(4, isDisabled);
	}
}
