/**
 * This class is generated by jOOQ
 */
package org.nazymko.road_to_b.dao;


import javax.annotation.Generated;

import org.nazymko.road_to_b.dao.tables.Driver;
import org.nazymko.road_to_b.dao.tables.DriverProps;
import org.nazymko.road_to_b.dao.tables.Point;
import org.nazymko.road_to_b.dao.tables.Sits;
import org.nazymko.road_to_b.dao.tables.Transport;
import org.nazymko.road_to_b.dao.tables.TransportProps;
import org.nazymko.road_to_b.dao.tables.Trip;


/**
 * Convenience access to all tables in road_to_b_dev
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table road_to_b_dev.driver
	 */
	public static final Driver DRIVER = org.nazymko.road_to_b.dao.tables.Driver.DRIVER;

	/**
	 * The table road_to_b_dev.driver_props
	 */
	public static final DriverProps DRIVER_PROPS = org.nazymko.road_to_b.dao.tables.DriverProps.DRIVER_PROPS;

	/**
	 * The table road_to_b_dev.point
	 */
	public static final Point POINT = org.nazymko.road_to_b.dao.tables.Point.POINT;

	/**
	 * The table road_to_b_dev.sits
	 */
	public static final Sits SITS = org.nazymko.road_to_b.dao.tables.Sits.SITS;

	/**
	 * The table road_to_b_dev.transport
	 */
	public static final Transport TRANSPORT = org.nazymko.road_to_b.dao.tables.Transport.TRANSPORT;

	/**
	 * The table road_to_b_dev.transport_props
	 */
	public static final TransportProps TRANSPORT_PROPS = org.nazymko.road_to_b.dao.tables.TransportProps.TRANSPORT_PROPS;

	/**
	 * The table road_to_b_dev.trip
	 */
	public static final Trip TRIP = org.nazymko.road_to_b.dao.tables.Trip.TRIP;
}
